apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: roboshop
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    env:
    - name: MESSAGE
      value: "hello world"
    command: ["/bin/sh","-c"]
    args: ["/bin/echo \"${MESSAGE}\""]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
